install:
- choco install gradle

build_script:
- gradle assemble

test_script:
- gradle check

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Users\appveyor\.gradle
